name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true
        default: 'version'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn package

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: spigot-plugin
          path: target/AlwaysNightVision-*.jar

      - name: Create GitHub Release
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          VERSION=${{ github.event.inputs.version }}
          if [ -z "$VERSION" ]; then
            echo "Version could not be detected!"
            exit 1
          fi
          echo "Using provided version: $VERSION"

          API_JSON=$(printf '{"tag_name": "%s","target_commitish": "main","name": "Release %s","body": "Release of version %s","draft": false,"prerelease": false}' $VERSION $VERSION $VERSION)
          curl -X POST -H "Authorization: token $GH_PAT" \
            -H "Content-Type: application/json" \
            -d "$API_JSON" \
            https://api.github.com/repos/${{ github.repository }}/releases
